import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Footer } from "@/components/home/footer";
import { Toaster } from "@/components/ui/sonner"
// import { PerformanceMonitor } from "@/components/PerformanceMonitor"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Finance Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* {process.env.NODE_ENV === 'development' && <PerformanceMonitor />} */}
        <Header />
        <main className="min-h-screen">{children}</main>
        <Toaster position="top-center" richColors />
        
      </body>
    </html>
  );
}
